[package]
name = "sajl"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { features = ["derive"], version = "1.0.228"}
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"]}
